//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMain
    {
        public int BookingId { get; set; }
        public string BookingNo { get; set; }
        public Nullable<System.DateTime> BookingSDate { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime DocRecDate { get; set; }
        public string BookingRecMode { get; set; }
        public string PaymentMode { get; set; }
        public string DeliveryPriority { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> EntryYear { get; set; }
        public int LocationId { get; set; }
        public short CategoryId { get; set; }
        public short CustomerId { get; set; }
        public string CustomerRef { get; set; }
        public string ContactName { get; set; }
        public string ContactNo { get; set; }
        public string ContactEmail { get; set; }
        public short AgentId { get; set; }
        public short RetailerId { get; set; }
        public byte RetCountryId { get; set; }
        public string RNNo { get; set; }
        public byte IsNominated { get; set; }
        public short ImporterId { get; set; }
        public short RepresentativeId { get; set; }
        public byte IsForImpression { get; set; }
        public string CommonInstruction { get; set; }
        public byte IsSpecialBooking { get; set; }
        public byte IsSpecification { get; set; }
        public byte IsSignature { get; set; }
        public byte IsLetterHP { get; set; }
        public byte IsCompleteDate { get; set; }
        public byte IsDeliveryPoint { get; set; }
        public byte IsUDRequired { get; set; }
        public byte IsIPRequired { get; set; }
        public byte IsWOUDIP { get; set; }
        public decimal USDRate { get; set; }
        public byte FactoryId { get; set; }
        public int BookingQId { get; set; }
        public byte IsHold { get; set; }
        public string HoldingReason { get; set; }
        public string Remarks { get; set; }
        public System.DateTime TransferDate { get; set; }
        public short TransferUserId { get; set; }
        public decimal BookingAmount { get; set; }
        public decimal DeliveredAmount { get; set; }
        public decimal ReturnAmount { get; set; }
        public decimal CancelAmount { get; set; }
        public byte IsPIDone { get; set; }
        public byte IsSMSSent { get; set; }
        public byte IsPrintDone { get; set; }
        public System.DateTime PrintTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short ConfirmUserId { get; set; }
        public System.DateTime ConfirmDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    
        public virtual CustomerGenInfo CustomerGenInfo { get; set; }
    }
}
