//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public byte CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string VatNo { get; set; }
        public string TinNo { get; set; }
        public string IRCNo { get; set; }
        public string ERCNo { get; set; }
        public string BINNo { get; set; }
        public string BONDNo { get; set; }
        public byte CountryId { get; set; }
        public string ShortName { get; set; }
        public string Prefix { get; set; }
        public string Type { get; set; }
        public string ShortType { get; set; }
        public short CategoryId { get; set; }
        public string PIMaterial { get; set; }
        public string Alias { get; set; }
        public byte IsActive { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    }
}
