//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRepInfo
    {
        public int CRLimitId { get; set; }
        public short CustomerId { get; set; }
        public short RepresentativeId { get; set; }
        public decimal SugCreditLimit { get; set; }
        public System.DateTime CreditSugDate { get; set; }
        public decimal AppCreditLimit { get; set; }
        public System.DateTime CreditAppDate { get; set; }
        public short CreditPeriod { get; set; }
        public byte IsBookingLock { get; set; }
        public string BLRemarks { get; set; }
        public byte IsSalesLock { get; set; }
        public string DLRemarks { get; set; }
        public byte IsScheduleLock { get; set; }
        public string SLRemarks { get; set; }
        public byte IsDefault { get; set; }
        public byte IsActive { get; set; }
        public int TakeOverRepId { get; set; }
        public byte IsScheduleLockForOC { get; set; }
        public System.DateTime ScheduleOpenDate { get; set; }
        public System.DateTime ScheduleCloseDate { get; set; }
        public string PaymentMode { get; set; }
        public byte IsUDRequired { get; set; }
        public byte IsIPRequired { get; set; }
        public byte IsWOUDIP { get; set; }
    
        public virtual CustomerGenInfo CustomerGenInfo { get; set; }
    }
}
