//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGenInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerGenInfo()
        {
            this.BookingMains = new HashSet<BookingMain>();
            this.CustomerRepInfoes = new HashSet<CustomerRepInfo>();
        }
    
        public short CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public short CustomerTypeId { get; set; }
        public short GroupId { get; set; }
        public short RepresentativeId { get; set; }
        public byte ZoneId { get; set; }
        public decimal Rating { get; set; }
        public short ClassId { get; set; }
        public decimal SugCreditLimit { get; set; }
        public System.DateTime CreditSugDate { get; set; }
        public decimal AppCreditLimit { get; set; }
        public System.DateTime CreditAppDate { get; set; }
        public short CreditPeriod { get; set; }
        public byte MinPriceLock { get; set; }
        public byte CreditLock { get; set; }
        public byte OIAllowed { get; set; }
        public byte TotalFactory { get; set; }
        public short TotalMachine { get; set; }
        public short TotalEmployee { get; set; }
        public decimal AnnualTurnover { get; set; }
        public byte IsApproved { get; set; }
        public byte IsActive { get; set; }
        public byte IsBookingLock { get; set; }
        public byte IsSalesLock { get; set; }
        public byte IsDorment { get; set; }
        public byte IsScheduleLock { get; set; }
        public byte IsWebSiteAllowed { get; set; }
        public byte IsAutoPIEnable { get; set; }
        public byte IsInBlock { get; set; }
        public byte IsInNonLCBlock { get; set; }
        public byte IsBillPI { get; set; }
        public System.DateTime PIStartDate { get; set; }
        public string VATRegNo { get; set; }
        public string TINNo { get; set; }
        public decimal MaxCommission { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
        public string CustId { get; set; }
        public short IFactoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMain> BookingMains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRepInfo> CustomerRepInfoes { get; set; }
    }
}
