//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMain
    {
        public int InvoiceId { get; set; }
        public int InvoiceSL { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<System.DateTime> InvoiceSDate { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public short CategoryId { get; set; }
        public int BookingId { get; set; }
        public string BookingNo { get; set; }
        public string CustomerRef { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime BookingDate { get; set; }
        public short CustomerId { get; set; }
        public short RepresentativeId { get; set; }
        public string RNNo { get; set; }
        public short RetailerId { get; set; }
        public short LocationId { get; set; }
        public string BBLC { get; set; }
        public Nullable<System.DateTime> BBLCDate { get; set; }
        public string MLC { get; set; }
        public System.DateTime MLCDate { get; set; }
        public int TransportId { get; set; }
        public string TransportName { get; set; }
        public int DriverEmpId { get; set; }
        public int TripNo { get; set; }
        public decimal USDRate { get; set; }
        public int CartoonQuantity { get; set; }
        public int DeliveryPointId { get; set; }
        public int DeliveryPointSId { get; set; }
        public string DeliveryAddress { get; set; }
        public string Remarks { get; set; }
        public byte IsReturnable { get; set; }
        public byte IsDislocation { get; set; }
        public int PackagingQRID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PcName { get; set; }
    }
}
