//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSub
    {
        public int InvoiceId { get; set; }
        public int InvoiceSubId { get; set; }
        public int BookingSubId { get; set; }
        public int InvoiceRelationId { get; set; }
        public int RelationId { get; set; }
        public short ProductId { get; set; }
        public string NSDNo { get; set; }
        public short MeasureUnitId { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Thickness { get; set; }
        public string Measurement { get; set; }
        public string PONumber { get; set; }
        public string StyleRef { get; set; }
        public string Color { get; set; }
        public string BreakDown1 { get; set; }
        public string BreakDown2 { get; set; }
        public string Size { get; set; }
        public short PackStyleId { get; set; }
        public string Perforation { get; set; }
        public int Ply { get; set; }
        public short PaperComId { get; set; }
        public string PaperCombination { get; set; }
        public string MaterialName { get; set; }
        public string DeptNoColor { get; set; }
        public string Sealing { get; set; }
        public decimal GsstLength { get; set; }
        public decimal GsstWidthLeft { get; set; }
        public decimal GsstWidthRight { get; set; }
        public string ShadeNumber { get; set; }
        public string ShadeOption { get; set; }
        public string WashType { get; set; }
        public string DyelotNo { get; set; }
        public string ItemCode { get; set; }
        public string LabelCaption { get; set; }
        public string Brand { get; set; }
        public decimal PackingQty { get; set; }
        public decimal InvoiceQty { get; set; }
        public decimal ReturnQty { get; set; }
        public decimal ScheduleQty { get; set; }
        public decimal ProduceQty { get; set; }
        public string PackingNote { get; set; }
        public short QtyUnitId { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Tax { get; set; }
        public decimal OtherCharge { get; set; }
        public decimal OI { get; set; }
        public string OIConfarm { get; set; }
        public decimal Commission { get; set; }
        public string CommConfirm { get; set; }
        public decimal MinPrice { get; set; }
        public decimal RegularPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Remarks { get; set; }
        public byte RelationType { get; set; }
    }
}
