//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIMain()
        {
            this.PISubs = new HashSet<PISub>();
        }
    
        public int PIId { get; set; }
        public string PINo { get; set; }
        public string PIPrefix { get; set; }
        public Nullable<System.DateTime> PISDate { get; set; }
        public System.DateTime PIDate { get; set; }
        public short PITypeId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public int LocationId { get; set; }
        public string BookingNo { get; set; }
        public byte CompanyId { get; set; }
        public short CustomerId { get; set; }
        public short IssuerId { get; set; }
        public string CustomerRef { get; set; }
        public string AddEmailAddress { get; set; }
        public short RepresentativeId { get; set; }
        public short CMRepresentativeId { get; set; }
        public short PIClauseId { get; set; }
        public byte AdvisingBankId { get; set; }
        public short AdvisingBranchId { get; set; }
        public short BillAddressId { get; set; }
        public string BillAddress { get; set; }
        public decimal PIAmount { get; set; }
        public byte IsCollectionDone { get; set; }
        public byte IsCustomizePI { get; set; }
        public byte IsPONumber { get; set; }
        public byte IsStyleRef { get; set; }
        public byte IsSize { get; set; }
        public byte IsColor { get; set; }
        public byte IsBreakdown1 { get; set; }
        public byte IsBreakdown2 { get; set; }
        public byte IsShadeNumber { get; set; }
        public byte IsWashType { get; set; }
        public byte IsGSM { get; set; }
        public byte IsAutoPI { get; set; }
        public byte IsSentToCustomer { get; set; }
        public byte IsInQueue { get; set; }
        public System.DateTime PIFwDate { get; set; }
        public byte IsWeightPI { get; set; }
        public byte IsBookingRevised { get; set; }
        public short SendingCount { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    
        public virtual PIMain PIMain1 { get; set; }
        public virtual PIMain PIMain2 { get; set; }
        public virtual PIMain PIMain11 { get; set; }
        public virtual PIMain PIMain3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PISub> PISubs { get; set; }
    }
}
