//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCategory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public short CategoryId { get; set; }
        public short GroupId { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string Alias { get; set; }
        public string ShortName { get; set; }
        public string Prefix { get; set; }
        public string RefName { get; set; }
        public byte IsBondedItem { get; set; }
        public int NSDCatId { get; set; }
        public string MeasureUnitList { get; set; }
        public string QuantityUnitList { get; set; }
        public short DefaultMUnitId { get; set; }
        public short DefaultQUnitId { get; set; }
        public byte IsActive { get; set; }
        public byte IsSampleEnable { get; set; }
        public byte RankSL { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
