//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public short ProductId { get; set; }
        public string ProductCode { get; set; }
        public short CategoryId { get; set; }
        public int NSDProdId { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string ShortName { get; set; }
        public string Prefix { get; set; }
        public string HSCode { get; set; }
        public string BondName { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal MinPrice { get; set; }
        public short FamilyCount { get; set; }
        public decimal ConePerPack { get; set; }
        public string CountGroup { get; set; }
        public string TktNo { get; set; }
        public string Text { get; set; }
        public string Article { get; set; }
        public short AgentId { get; set; }
        public byte IsAgentInactive { get; set; }
        public byte IsActive { get; set; }
        public short FormulaGroupId { get; set; }
        public string FormulaGroup { get; set; }
        public string FGProdId { get; set; }
        public string ProdId { get; set; }
        public decimal NetWeight { get; set; }
        public decimal NetWeightNew { get; set; }
        public string Remarks { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
