//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representative
    {
        public short RepresentativeId { get; set; }
        public int Category { get; set; }
        public string ShortName { get; set; }
        public string RepresentativeName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public short TeamId { get; set; }
        public int EmployeeId { get; set; }
        public byte ADM { get; set; }
        public short LocationId { get; set; }
        public byte ProductionZoneId { get; set; }
        public string OldSalesId { get; set; }
        public byte IsActive { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
        public string PCName { get; set; }
    }
}
