//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public short RetailerId { get; set; }
        public string RetailerName { get; set; }
        public string ShortName { get; set; }
        public byte CountryId { get; set; }
        public string HOAddress { get; set; }
        public string WebAddress { get; set; }
        public string BusinessType { get; set; }
        public string LocOffAddress { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public short IsAdm { get; set; }
        public byte IsSMSSendToADM { get; set; }
        public byte IsAllCustomerSMS { get; set; }
        public byte IsEmailSendToADM { get; set; }
        public byte IsAllCustomerEmail { get; set; }
        public byte IsActive { get; set; }
        public short EntryUserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public short RevisionUserId { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public string IPAddress { get; set; }
    }
}
