//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenuPermission
    {
        public short UserId { get; set; }
        public string UserName { get; set; }
        public string UserTitle { get; set; }
        public string DepartmentName { get; set; }
        public string MenuTitle { get; set; }
        public string Previlize { get; set; }
    }
}
