//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDN
    {
        public string FileNo { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string MasterLc { get; set; }
        public string CustomerName { get; set; }
        public decimal CollectionAmount { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string IssuerName { get; set; }
        public string RepresentativeName { get; set; }
        public string DNNo { get; set; }
        public decimal DNAmount { get; set; }
        public string ForwardTo { get; set; }
        public System.DateTime ForwardDate { get; set; }
        public string AccecptName { get; set; }
        public System.DateTime AcceptDate { get; set; }
    }
}
