//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPaperCombination
    {
        public short PaperComId { get; set; }
        public string PaperComName { get; set; }
        public short ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public byte Ply { get; set; }
        public string CombinationDetails { get; set; }
        public short PaperId { get; set; }
        public string PaperCode { get; set; }
        public string PaperName { get; set; }
        public byte IsCorrogated { get; set; }
        public byte Quantity { get; set; }
        public byte RowNo { get; set; }
    }
}
