//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIewSlpSale
    {
        public Nullable<int> YearID { get; set; }
        public string RetailerName { get; set; }
        public string Alias { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Tag { get; set; }
    }
}
