//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewRepresentativeType
    {
        public short RepresentativeTypeId { get; set; }
        public string RepresentativeType { get; set; }
        public byte IsActive { get; set; }
    }
}
