//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCompanyAccount
    {
        public byte CompanyId { get; set; }
        public string CompanyName { get; set; }
        public short CategoryId { get; set; }
        public string CategoryName { get; set; }
        public byte AccountId { get; set; }
        public string SwiftCode { get; set; }
        public byte BankId { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public short BranchId { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public byte IsActive { get; set; }
    }
}
