//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOIBillPaymentData
    {
        public int OIBillConfirmId { get; set; }
        public int InstructionId { get; set; }
        public string InstructionNo { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string IssueTo { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<int> ChequeId { get; set; }
        public string ChequeNo { get; set; }
        public string OIConfirmNo { get; set; }
        public Nullable<int> OIBillId { get; set; }
        public string OIBIllNo { get; set; }
        public Nullable<System.DateTime> OIBillDate { get; set; }
        public Nullable<int> OIBILLFevSubId { get; set; }
    }
}
