//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCustomerProfile
    {
        public string genName { get; set; }
        public string genRepName { get; set; }
        public string genGroupName { get; set; }
        public string genZone { get; set; }
        public string genClass { get; set; }
        public decimal genSugCreditLimit { get; set; }
        public decimal genAppCreditLimit { get; set; }
        public short genCreditPeriod { get; set; }
        public byte genMinPriceLock { get; set; }
        public byte genCreditLock { get; set; }
        public byte genOIAllowed { get; set; }
        public byte genTotalFactory { get; set; }
        public short genTotalMachine { get; set; }
        public short genTotalEmployee { get; set; }
        public decimal genAnnualTurnover { get; set; }
        public byte genIsApproved { get; set; }
        public byte genIsBookingLock { get; set; }
        public byte IsSalesLock { get; set; }
        public byte genIsDorment { get; set; }
        public byte genIsWebSiteAllowed { get; set; }
        public string genVATRegNo { get; set; }
        public string genTINNo { get; set; }
        public decimal genMaxCommission { get; set; }
        public string KCName { get; set; }
        public string KCPosition { get; set; }
        public string KCDepartment { get; set; }
        public string KCTelephone { get; set; }
        public string KCMObile { get; set; }
        public string KCEmail { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime kcAnniversaryDate { get; set; }
        public string KCDistrict { get; set; }
        public string kcResidenceAdd { get; set; }
        public decimal ebBusinessAmount { get; set; }
        public string ocname { get; set; }
        public string ocPosition { get; set; }
        public string ocDepartment { get; set; }
        public string OcTelephone { get; set; }
        public string ocMobile { get; set; }
        public string ocEmail { get; set; }
        public string obBusinessType { get; set; }
        public string obCompanyName { get; set; }
        public string obBankName { get; set; }
        public string obBranchName { get; set; }
        public string ccName { get; set; }
        public string ccAddressFirst { get; set; }
        public string ccAddressTwo { get; set; }
        public string ccArea { get; set; }
        public string ccCity { get; set; }
        public string ccCountryName { get; set; }
        public string ccTelephoneOne { get; set; }
        public string ccTelephoneTwo { get; set; }
        public string ccFax { get; set; }
        public string ccEmail { get; set; }
        public string ccWebsite { get; set; }
    }
}
