//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEmailList
    {
        public Nullable<long> EmailListId { get; set; }
        public short UserId { get; set; }
        public string UserName { get; set; }
        public string eMail { get; set; }
        public short UserTypeId { get; set; }
        public string ShortUserType { get; set; }
        public string UserType { get; set; }
        public short UserLevelId { get; set; }
        public string UserLevel { get; set; }
        public short LocationId { get; set; }
    }
}
