//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewClauseDetail
    {
        public short ClauseId { get; set; }
        public string ClauseCode { get; set; }
        public string ClauseName { get; set; }
        public byte TermId { get; set; }
        public string TermName { get; set; }
        public short ConditionId { get; set; }
        public string ConditionDetails { get; set; }
        public string ConditionDetailsHTML { get; set; }
        public byte RowNo { get; set; }
        public byte IsActive { get; set; }
    }
}
