//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewSalesRepWisePBI
    {
        public string year { get; set; }
        public string MONTH { get; set; }
        public string ShortName { get; set; }
        public string LocationName { get; set; }
        public Nullable<decimal> Booking { get; set; }
        public Nullable<decimal> Sales_Value { get; set; }
    }
}
