//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewBookingDetail
    {
        public int BookingId { get; set; }
        public string BookingNo { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime DocRecDate { get; set; }
        public int BookingSubId { get; set; }
        public int BookingRelationId { get; set; }
        public int RelationId { get; set; }
        public short ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string BookingRecMode { get; set; }
        public string PaymentMode { get; set; }
        public string DeliveryPriority { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public int LocationId { get; set; }
        public short CategoryId { get; set; }
        public short CustomerId { get; set; }
        public string CustomerRef { get; set; }
        public string ContactName { get; set; }
        public string ContactNo { get; set; }
        public short AgentId { get; set; }
        public short RetailerId { get; set; }
        public byte RetCountryId { get; set; }
        public string RNNo { get; set; }
        public byte IsNominated { get; set; }
        public short ImporterId { get; set; }
        public short RepresentativeId { get; set; }
        public byte IsUDRequired { get; set; }
        public byte IsIPRequired { get; set; }
        public byte IsWOUDIP { get; set; }
        public decimal USDRate { get; set; }
        public byte FactoryId { get; set; }
        public int BookingQId { get; set; }
        public byte IsHold { get; set; }
        public string HoldingReason { get; set; }
        public string Remarks { get; set; }
        public decimal BookingAmount { get; set; }
        public decimal DeliveredAmount { get; set; }
        public decimal ReturnAmount { get; set; }
        public decimal CancelAmount { get; set; }
        public byte IsPIDone { get; set; }
        public string NSDNo { get; set; }
        public short MeasureUnitId { get; set; }
        public string MeasureUnit { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Thickness { get; set; }
        public string Measurement { get; set; }
        public string PONumber { get; set; }
        public string StyleRef { get; set; }
        public string Color { get; set; }
        public string BreakDown1 { get; set; }
        public string BreakDown2 { get; set; }
        public string Size { get; set; }
        public short PackStyleId { get; set; }
        public byte Ply { get; set; }
        public decimal SqrMeter { get; set; }
        public byte IsPerforated { get; set; }
        public short PaperComId { get; set; }
        public string PaperCombination { get; set; }
        public string GlueType { get; set; }
        public string ElasticType { get; set; }
        public byte IsPrinted { get; set; }
        public byte IsOutDimension { get; set; }
        public byte IsDyeCutting { get; set; }
        public string MaterialName { get; set; }
        public string DeptNoColor { get; set; }
        public string Sealing { get; set; }
        public byte AirHole { get; set; }
        public decimal PillowSize { get; set; }
        public decimal Flap { get; set; }
        public decimal GsstLength { get; set; }
        public decimal GsstWidthLeft { get; set; }
        public decimal GsstWidthRight { get; set; }
        public decimal PrintCost { get; set; }
        public decimal AdhesiveCost { get; set; }
        public string PrintOption { get; set; }
        public string NoOfColor { get; set; }
        public string ShadeNumber { get; set; }
        public string ShadeOption { get; set; }
        public string WashType { get; set; }
        public string ItemCode { get; set; }
        public string LabelCaption { get; set; }
        public string Brand { get; set; }
        public string Cut_Fold { get; set; }
        public string GSM { get; set; }
        public byte IsSymbol { get; set; }
        public byte IsCountryOfOrigin { get; set; }
        public byte IsAddWashCare { get; set; }
        public byte IsWashBox { get; set; }
        public byte IsKAFF { get; set; }
        public byte IsFiberContent { get; set; }
        public byte IsAWSupplied { get; set; }
        public byte IsAWSpecification { get; set; }
        public decimal BookingQty { get; set; }
        public decimal InvoiceQty { get; set; }
        public decimal CancelQty { get; set; }
        public decimal ReturnQty { get; set; }
        public short QtyUnitId { get; set; }
        public string QuantityUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal OI { get; set; }
        public decimal ExcessAmount { get; set; }
        public decimal KGPerUnit { get; set; }
        public Nullable<decimal> QtyInKG { get; set; }
        public short PcsPerUnit { get; set; }
        public Nullable<decimal> QtyInPcs { get; set; }
        public decimal UnitPriceKG { get; set; }
        public decimal MinPrice { get; set; }
        public decimal RegularPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public short DeliveryPointSId { get; set; }
        public System.DateTime CancelDate { get; set; }
        public System.DateTime DeliveryDate1 { get; set; }
        public System.DateTime DeliveryDate2 { get; set; }
        public string PrintInstructionFS { get; set; }
        public string PrintInstructionBS { get; set; }
        public short RowNo { get; set; }
        public byte RelationType { get; set; }
    }
}
