//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIAdvisingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtest
    {
        public int BookingId { get; set; }
        public short ProductId { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string StyleRef { get; set; }
        public string Color { get; set; }
        public byte Ply { get; set; }
        public string Size { get; set; }
        public string Measurement { get; set; }
        public string UnitType { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal OI { get; set; }
        public decimal BookingQty { get; set; }
        public int DeliveryQty { get; set; }
    }
}
